version: '3.8'

services:
  train-router:
    image: train-router
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgres/trainRouter
      - DB_USER=app
      - DB_PASSWORD=SH31vd256zPBNs
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: SH31vd256zPBNs
      POSTGRES_DB: trainRouter
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: